learn_templates/basicapp/urls.py
from django.conf.urls import url
from django.urls import include, path
from basicapp import views

# TEMPLATE TAGGING

app_name = 'basicapp'

urlpatterns = [
    path('relative/', views.relative, name='relative'),
    path('other/', views.other, name='other'),

]

learn_templates/learn_templates/urls.py
from django.contrib import admin
from django.urls import include, path
from basicapp import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('basicapp/', include('basicapp.urls')),
]

learn_templates/basicapp/models.py
from django.db import models

# Create your models here.

learn_templates/basicapp/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    context_dict = {'text':'Hello world','number':100}
    return render(request, 'basicapp/index.html',context_dict)


def other(request):
    return render(request, 'basicapp/other.html')


def relative(request):
    return render(request, 'basicapp/relative_url_templates.html')

learn_templates/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <title></title>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>

<body>
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <ul class="nav navbar-nav">
        <li><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
        <li><a class="navbar-link" href="{% url 'admin:index' %}">ADMIN</a></li>
        <li><a class="navbar-link" href="{% url 'basicapp:other' %}">OTHER</a></li>

      </ul>
      <div class="container">

      </div>
      {% block body_block %}
      <!-- Anything outside of this will be inherited if you extend! -->
      {% endblock %}

    </div>

  </nav>
</body>

</html>

learn_templates/templates/basicapp/index.html
<!DOCTYPE html>

{% extends "basicapp/base.html" %}
{% block body_block %}

<h1>WELCOME TO INDEX</h1>
{# <h2>{{ text|upper }}</h2> #}
<h2>{{ text|cut:'world' }}</h2>
<h2>{{ number|add:'99' }}</h2>
{% endblock %}

learn_templates/templates/basicapp/other.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
{% block body_block %}
<h1>WELCOME TO OTHERS</h1>
<h2>This is an example of template inherirance!</h2>
{% endblock %}

learn_templates/templates/basicapp/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <title></title>
</head>

<body>
  <h1>WELCOME TO RELATIVE URL TEMPLATES</h1>
  <a href="{% url 'basicapp:other' %}">THE OTHER PAGE</a>
  <br>
  <a href="{% url 'admin:index' %}">LINK TO ADMIN</a>
  <br>
  <a href="{% url 'index' %}">LINK INDEX</a>
  <h1>hi</h1>
</body>

</html>